usage: call_gpt2.py [-h] [--key KEY] [--data_path DATA_PATH] [--prompt PROMPT]
                    [--type TYPE]
call_gpt2.py: error: unrecognized arguments: ca
